remove boost, un-error libexpat

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -15,27 +15,18 @@ jobs:
         fetch-depth: 0
     - name: Install deps
       run: |
-        git clone https://github.com/cmake-remake/zlib.git
+        git clone https://github.com/madler/zlib.git
         cmake -S zlib -B zlib-build -DZLIB_BUILD_MINIZIP=ON -DMINIZIP_ENABLE_BZIP2=OFF -DCMAKE_INSTALL_PREFIX=D:/a/libkml/Install
         cmake --build zlib-build -v --config Release
         cmake --install zlib-build --config Release
-        git clone https://github.com/boostorg/boost.git
-        cd boost
-        git submodule init libs/assert libs/config libs/core libs/move
-        git submodule init libs/smart_ptr libs/static_assert
-        git submodule init libs/throw_exception libs/type_traits tools/cmake
-        git submodule init libs/headers libs/smart_ptr
-        git submodule update libs/assert libs/config libs/core libs/move
-        git submodule update libs/smart_ptr libs/static_assert
-        git submodule update libs/throw_exception libs/type_traits
-        git submodule update tools/cmake libs/headers libs/smart_ptr
-        cd ..
-        cmake -S boost -B boost-build -DBOOST_INCLUDE_LIBRARIES=smart_ptr -DCMAKE_INSTALL_PREFIX=D:/a/libkml/Install
-        cmake --build boost-build --config Release
-        cmake --install boost-build --config Release
         git clone https://github.com/libexpat/libexpat.git
         cd libexpat
-        git checkout R_2_6_3
+        # Pinned master commit: all releases up to R_2_7_3 detect arc4random_buf()
+        # in GNU mode but compile with -std=c99, where newlib/BSD headers hide the
+        # declaration; GCC >= 14 turns that into a hard error (broke the Cygwin
+        # job). Master isolates the entropy code with proper feature-test macros.
+        # Switch back to a release tag once one containing this rework is out.
+        git checkout b68595d07cc869af802964709dea6b232d39e56e
         cd ..
         cmake -S libexpat/expat -B expat-build -DCMAKE_INSTALL_PREFIX=D:/a/libkml/Install
         cmake --build expat-build --config Release
@@ -78,8 +69,8 @@ jobs:
         fetch-depth: 0
     - name: Install Deps
       run: |
-        sudo apt install libboost-dev libbz2-dev liburiparser-dev googletest
-        git clone https://github.com/cmake-remake/zlib.git
+        sudo apt install libbz2-dev liburiparser-dev googletest
+        git clone https://github.com/madler/zlib.git
         cmake -S zlib -B zlib-build -DCMAKE_BUILD_TYPE=Release -DZLIB_BUILD_MINIZIP=ON
         cmake --build zlib-build
         sudo cmake --install zlib-build
@@ -110,39 +101,7 @@ jobs:
         fetch-depth: 0
     - name: Install deps
       run: |
-        git clone https://github.com/boostorg/boost.git
-        cd boost
-        git checkout boost-1.87.0
-        git submodule init libs/assert \
-          libs/config \
-          libs/core \
-          libs/move \
-          libs/smart_ptr \
-          libs/static_assert \
-          libs/throw_exception \
-          libs/type_traits \
-          tools/cmake \
-          libs/headers \
-          libs/smart_ptr
-        git submodule update libs/assert \
-          libs/config \
-          libs/core \
-          libs/move \
-          libs/smart_ptr \
-          libs/static_assert \
-          libs/throw_exception \
-          libs/type_traits \
-          tools/cmake \
-          libs/headers \
-          libs/smart_ptr
-        cd ..
-        cmake -S boost \
-          -B boost-build \
-          -DBOOST_INCLUDE_LIBRARIES=smart_ptr \
-          -DCMAKE_INSTALL_PREFIX=/Users/runner/Install
-        cmake --build boost-build
-        cmake --install boost-build
-        git clone https://github.com/cmake-remake/zlib.git
+        git clone https://github.com/madler/zlib.git
         cmake -S zlib \
           -B zlib-build \
           -DCMAKE_BUILD_TYPE=Release \
@@ -153,7 +112,8 @@ jobs:
         cmake --install zlib-build
         git clone https://github.com/libexpat/libexpat.git
         cd libexpat
-        git checkout R_2_6_3
+        # Pinned master commit, see comment in the Windows job.
+        git checkout b68595d07cc869af802964709dea6b232d39e56e
         cd ..
         cmake -S libexpat/expat \
           -B expat-build \
@@ -214,7 +174,6 @@ jobs:
         pacboy: >-
           toolchain:p
           cmake:p
-          boost:p
     - name: Install deps
       run: |
         if [ ${MSYSTEM} == CLANG64 ]
@@ -222,7 +181,7 @@ jobs:
           export CC=clang
           export CXX=clang++
         fi
-        git clone https://github.com/cmake-remake/zlib.git
+        git clone https://github.com/madler/zlib.git
         cmake -S zlib \
           -B zlib-build \
           -DCMAKE_BUILD_TYPE=Release \
@@ -272,7 +231,9 @@ jobs:
     runs-on: windows-latest
     defaults:
       run:
-        shell: C:\cygwin\bin\bash.exe --login -o igncr '{0}'
+        # -e so a failing dependency build stops the step right there instead of
+        # surfacing later as a missing package at configure time.
+        shell: C:\cygwin\bin\bash.exe --login -o igncr -eo pipefail '{0}'
     name: Cygwin
     steps:
     - name: Checkout
@@ -288,10 +249,9 @@ jobs:
           gcc-core
           gcc-g++
           ninja
-          boost
     - name: Install deps
       run: |
-        git clone https://github.com/cmake-remake/zlib.git
+        git clone https://github.com/madler/zlib.git
         cmake -S zlib \
           -GNinja \
           -B zlib-build \
@@ -300,39 +260,11 @@ jobs:
           -DMINIZIP_ENABLE_BZIP2=OFF
         cmake --build zlib-build -v -j1
         cmake --install zlib-build
-        git clone https://github.com/boostorg/boost.git
-        cd boost
-        git submodule init libs/assert \
-          libs/config \
-          libs/core \
-          libs/move \
-          libs/smart_ptr \
-          libs/static_assert \
-          libs/throw_exception \
-          libs/type_traits \
-          tools/cmake \
-          libs/headers \
-          libs/smart_ptr
-        git submodule update libs/assert \
-          libs/config \
-          libs/core \
-          libs/move \
-          libs/smart_ptr \
-          libs/static_assert \
-          libs/throw_exception \
-          libs/type_traits \
-          tools/cmake \
-          libs/headers \
-          libs/smart_ptr
-        cd ..
-        cmake -S boost \
-          -B boost-build \
-          -DBOOST_INCLUDE_LIBRARIES=smart_ptr
-        cmake --build boost-build
-        cmake --install boost-build
         git clone https://github.com/libexpat/libexpat.git
         cd libexpat
-        git checkout R_2_6_3
+        # Pinned master commit, see comment in the Windows job. Cygwin is where
+        # the release versions actually break (GCC >= 14 + newlib).
+        git checkout b68595d07cc869af802964709dea6b232d39e56e
         cd ..
         cmake -S libexpat/expat \
           -B expat-build \
